source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MapsIndoors_Example', :exclusive => true do
  pod "MapsIndoors", :path => "../"
  
  pod 'AFNetworking', '~> 2.5'
  pod 'MaterialControls', '~> 1.0'
  pod 'VCMaterialDesignIcons', '~> 2.1'
  pod 'GoogleFontsiOS/Roboto'
  pod 'HashBuilder', '~> 1.0'
  pod 'OCGoogleDirectionsAPI', '~> 0.1'
  pod 'EasyTableView', '~> 1.1'
  
  platform :ios, '8.1'
  pod 'GoogleMaps'
  
end

target 'MapsIndoors_Tests', :exclusive => true do
  pod "MapsIndoors", :path => "../"

    pod 'AFNetworking', '~> 2.5'
    pod 'MaterialControls', '~> 1.0'
    pod 'VCMaterialDesignIcons', '~> 2.1'
    pod 'GoogleFontsiOS/Roboto'
    pod 'HashBuilder', '~> 1.0'
    pod 'OCGoogleDirectionsAPI', '~> 0.1'
    pod 'EasyTableView', '~> 1.1'

    platform :ios, '8.1'
    pod 'GoogleMaps'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  
end
