platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def miaios_deps
    
    pod 'Firebase/Core'
    pod 'AFNetworking/Reachability', '~> 2.6'
    pod 'VCMaterialDesignIcons', '~> 2.1'
    pod 'GoogleFontsiOS/Roboto'
    pod 'HashBuilder', '~> 1.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'PureLayout', '~> 3.0.2'
    pod 'KVOController', '~> 1.2.0'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
    pod 'MaterialControls'
    #pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :tag => '2.0.0'

end

target 'MapsIndoors GitHub App' do
    miaios_deps
    pod 'GoogleMaps'
    pod 'MapsIndoors', :path => '../'
end

target 'Demos' do
    pod 'GoogleMaps'
    pod 'MapsIndoors', :path => '../'
end

target 'DemosUITests' do
    pod 'GoogleMaps'
    pod 'MapsIndoors', :path => '../'
end

target 'MIAIOSUITests' do
    pod 'GoogleMaps'
    pod 'MapsIndoors', :path => '../'
end


