platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

def miaios_deps
    

    pod 'MapsIndoors', :path => '../'
    
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    
    pod 'AFNetworking/Reachability', '~> 2.6'
    pod 'VCMaterialDesignIcons', '~> 2.1'
    pod 'HashBuilder', '~> 1.0'
    pod 'PureLayout', '~> 3.0.2'
    pod 'KVOController', '~> 1.2.0'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
    pod 'MapsIndoors', :path => '../'
    pod 'SVGKit'

end

target 'MapsIndoors GitHub App' do
    miaios_deps
end

target 'Demos' do
    miaios_deps
end

target 'DemosUITests' do
    miaios_deps
end

target 'MIAIOSUITests' do
    miaios_deps
end


