// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MIBaseType)
{
    MIBaseTypePOI,
    MIBaseTypeRoom,
    MIBaseTypeArea,
    MIBaseTypeFloor,
    MIBaseTypeBuilding,
    MIBaseTypeVenue,
    MIBaseTypeAsset,
};
