// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MICoordinate.h"
#import <Foundation/Foundation.h>

/** Geographical bounds model, defined by a south-western and a north-eastern corner coordinate.; */
@interface MICoordinateBounds : NSObject
- (nonnull instancetype)initWithNortheast:(nonnull MICoordinate *)northeast
                                southwest:(nonnull MICoordinate *)southwest;
+ (nonnull instancetype)CoordinateBoundsWithNortheast:(nonnull MICoordinate *)northeast
                                            southwest:(nonnull MICoordinate *)southwest;

/** North-eastern corner coordinate.; */
@property (nonatomic, readonly, nonnull) MICoordinate * northeast;

/** South-western corner coordinate.; */
@property (nonatomic, readonly, nonnull) MICoordinate * southwest;

@end
