// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

/** Geometry type. Point is currently the only supported type.; */
typedef NS_ENUM(NSInteger, MIGeometryType)
{
    MIGeometryTypePoint,
    MIGeometryTypePolygon,
    MIGeometryTypeMultiPolygon,
};
