// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MICoordinate.h"
#import "MICoordinateBounds.h"
#import <Foundation/Foundation.h>

/** Geometry model; */
@interface MIGeometry : NSObject
- (nonnull instancetype)initWithPosition:(nonnull MICoordinate *)position
                                  bounds:(nonnull MICoordinateBounds *)bounds;
+ (nonnull instancetype)GeometryWithPosition:(nonnull MICoordinate *)position
                                      bounds:(nonnull MICoordinateBounds *)bounds;

/** Geographic anchor position.; */
@property (nonatomic, readonly, nonnull) MICoordinate * position;

/** Geographic bounds; */
@property (nonatomic, readonly, nonnull) MICoordinateBounds * bounds;

@end
