// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MILocationStatus.h"
#import "MITextProperty.h"
#import <Foundation/Foundation.h>

/**
 * The `Group` class refers to a group/category concept. A `Location` can be part of 0-n groups. ;
 * Group membership is contributing to the search matching algorithm. So if a Group has the name property of "office", when searching for "office", all locations that is part of that group is considered relevant to some degree.;
 * Groups can hold a `LocationStatus` as well. If a group has the status of `ForceInactive` all members of that group is `Inactive` regardless of the locations own status.;
 */
@interface MIGroup : NSObject
- (nonnull instancetype)initWithGroupId:(int32_t)groupId
                                aliases:(nonnull NSArray<NSString *> *)aliases
                             properties:(nonnull NSArray<MITextProperty *> *)properties
                                 status:(MILocationStatus)status;
+ (nonnull instancetype)GroupWithGroupId:(int32_t)groupId
                                 aliases:(nonnull NSArray<NSString *> *)aliases
                              properties:(nonnull NSArray<MITextProperty *> *)properties
                                  status:(MILocationStatus)status;

/** Group id; */
@property (nonatomic, readonly) int32_t groupId;

/** Group aliases used as alternate search terms when searching for locations; */
@property (nonatomic, readonly, nonnull) NSArray<NSString *> * aliases;

/** Group properties, such as images, description etc.; */
@property (nonatomic, readonly, nonnull) NSArray<MITextProperty *> * properties;

/** Group status; */
@property (nonatomic, readonly) MILocationStatus status;

@end
