// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import <Foundation/Foundation.h>

/** Highway type classification = record; */
typedef NS_ENUM(NSInteger, MIHighwayType)
{
    /**Unclassified path type; */
    MIHighwayTypeUnclassified,
    /**Footway path type. Used most places in the indoor part of our route network.; */
    MIHighwayTypeFootway,
    /**Residential path type. Used most places in the indoor part of our route network.; */
    MIHighwayTypeResidential,
    /**Service path type. Used some places in the outdoor part of our route network.; */
    MIHighwayTypeService,
    /**Ramp path type. Used where there is a ramp or hill of some kind.; */
    MIHighwayTypeRamp,
    /**Steps path type. Used where there is steps, stairs or staircases.; */
    MIHighwayTypeSteps,
    /**Escalator path type.; */
    MIHighwayTypeEscalator,
    /**Travelator path type.; */
    MIHighwayTypeTravelator,
    /**Elevator path type.; */
    MIHighwayTypeElevator,
    /**Wheelchair ramp path type. Used where there is a wheelchair ramp.; */
    MIHighwayTypeWheelChairRamp,
    /**Wheelchair lift path type. Used where there is a wheelchair lift.; */
    MIHighwayTypeWheelChairLift,
    /**Ladder path type. Used where there is a ladder, fixed or movable.; */
    MIHighwayTypeLadder,
};
