// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

/** `LocationStatus` is a state model that determines whether a location is active or inactive.; */
typedef NS_OPTIONS(NSUInteger, MILocationStatus)
{
    MILocationStatusActive = 1 << 0,
    MILocationStatusSearchable = 1 << 1,
    MILocationStatusForceInactive = 1 << 2,
};
