// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MISize.h"
#import <Foundation/Foundation.h>


/** name: MapsIndoors Models; */
@protocol MILocationClusteringEngineDelegate

- (nonnull MISize *)sizeForClusterCount:(int32_t)count
                              clusterId:(nonnull NSString *)clusterId;

- (BOOL)clusteringIsCancelled;

@end
