// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MICoordinate.h"
#import "MIRect.h"
#import <Foundation/Foundation.h>

/** Cluster model. Contains a reference to the clustered locations, a rectangle in screen coordinates for the cluster, and the geographical coordinate for the cluster.; */
@interface MILocationCluster : NSObject
- (nonnull instancetype)initWithClusteredObjects:(nonnull NSArray<NSNumber *> *)clusteredObjects
                                     clusterRect:(nonnull MIRect *)clusterRect
                                      coordinate:(nonnull MICoordinate *)coordinate;
+ (nonnull instancetype)LocationClusterWithClusteredObjects:(nonnull NSArray<NSNumber *> *)clusteredObjects
                                                clusterRect:(nonnull MIRect *)clusterRect
                                                 coordinate:(nonnull MICoordinate *)coordinate;

/** References to the clustered locations.; */
@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * clusteredObjects;

/** A rectangle in screen coordinates for the cluster.; */
@property (nonatomic, readonly, nonnull) MIRect * clusterRect;

/** The geographical coordinate for the cluster.; */
@property (nonatomic, readonly, nonnull) MICoordinate * coordinate;

@end
