// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MILocationCluster.h"
#include "../cpp/LocationCluster.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MILocationCluster;

namespace djinni_generated {

struct LocationCluster
{
    using CppType = ::MICommon::LocationCluster;
    using ObjcType = MILocationCluster*;

    using Boxed = LocationCluster;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
