// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

/**
 * Available      	available and expected to provide data;
 * Unavailable    	unavailable but expected to provide data under normal circumstances;
 * Initialising   	processing and expected to provide data when initialised;
 * Not_Initialised Not expected to provide data. Expected to transition to another state;
 * Complete       The location service is ready to be used;
 */
typedef NS_ENUM(NSInteger, MILocationSourceStatus)
{
    /**Available status. The location source is expected to provide data but may not have data from all data sources yet; */
    MILocationSourceStatusAvailable,
    /**Unavailable status. The location source is not currently available but expected to provide data under normal circumstances.; */
    MILocationSourceStatusUnavailable,
    /**Initialising status. The location source is processing and expected to provide data when initialised.; */
    MILocationSourceStatusInitialising,
    /**Not_Initialised status. The location source is not expected to provide data, but expected to transition to another state.; */
    MILocationSourceStatusNotInitialized,
    /**Complete status. The location service is ready to be used */
    MILocationSourceStatusComplete
};
