// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIFilter.h"
#import "MIGroup.h"
#import "MIQuery.h"
#import <Foundation/Foundation.h>
@class MILocationService;
@protocol MILocationSource;
@protocol MILocationsObserver;


/**
 * name: MapsIndoors Models;
 * The `LocationService` acts as service for search and filtering in the full, aggregated collection of Locations, both internal MapsIndoors and external, provided by other location sources.;
 */
@interface MILocationService : NSObject

- (nonnull NSArray<NSNumber *> *)getLocations:(nonnull MIQuery *)query
                                       filter:(nonnull MIFilter *)filter;

+ (nullable MILocationService *)create;

- (void)registerLocationSources:(nonnull NSArray<id<MILocationSource>> *)sources;

- (void)addLocationsObserver:(nullable id<MILocationsObserver>)observer;

- (void)removeLocationsObserver:(nullable id<MILocationsObserver>)observer;

- (void)setGroups:(nonnull NSArray<MIGroup *> *)groups;

@end
