// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#include "../cpp/LocationClusteringEngine.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MILocationClusteringEngine;

namespace djinni_generated {

class LocationClusteringEngine
{
public:
    using CppType = std::shared_ptr<::MICommon::LocationClusteringEngine>;
    using CppOptType = std::shared_ptr<::MICommon::LocationClusteringEngine>;
    using ObjcType = MILocationClusteringEngine*;

    using Boxed = LocationClusteringEngine;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

