// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MICoordinate.h"
#import "MIPoint.h"
#import "MIRect.h"
#import <Foundation/Foundation.h>

/**
 *################################################# CLUSTERING OBJECTS AND DEPENDENCIES  ########################################################
 * Display metadata for a location, used as input to the `LocationClusteringEngine.computeClusters()` method.;
 */
@interface MILocationDisplayMetadata : NSObject
- (nonnull instancetype)initWithLocationTag:(int32_t)locationTag
                                markerPoint:(nonnull MIPoint *)markerPoint
                               clusteringId:(nonnull NSString *)clusteringId
                                displayRank:(int32_t)displayRank
                            markerImageRect:(nonnull MIRect *)markerImageRect
                                targetAlpha:(float)targetAlpha
                                 coordinate:(nonnull MICoordinate *)coordinate;
+ (nonnull instancetype)LocationDisplayMetadataWithLocationTag:(int32_t)locationTag
                                                   markerPoint:(nonnull MIPoint *)markerPoint
                                                  clusteringId:(nonnull NSString *)clusteringId
                                                   displayRank:(int32_t)displayRank
                                               markerImageRect:(nonnull MIRect *)markerImageRect
                                                   targetAlpha:(float)targetAlpha
                                                    coordinate:(nonnull MICoordinate *)coordinate;

/** The location tag. A id reference to a location instance.; */
@property (nonatomic, readonly) int32_t locationTag;

/** Marker point in screen coordinates.; */
@property (nonatomic, readonly, nonnull) MIPoint * markerPoint;

/** Clustering id. Locations that is assigned with the same clustering id may be clustered together. Locations with different clustering id will never be clustered together.; */
@property (nonatomic, readonly, nonnull) NSString * clusteringId;

/** Display rank. A number that is used to sort the items that needs clustering. High rank locations are less likely to be clustered.; */
@property (nonatomic, readonly) int32_t displayRank;

/** Marker image rectancle specified in screen coordinates.; */
@property (nonatomic, readonly, nonnull) MIRect * markerImageRect;

/** Target alpha is the value;     */
@property (nonatomic, readonly) float targetAlpha;

/** The geographical coordinate of the location.; */
@property (nonatomic, readonly, nonnull) MICoordinate * coordinate;

@end
