// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from HittesterInterface.djinni

#import <Foundation/Foundation.h>
@class MIObjectBoundingboxHittester;


/**
 * name: MapsIndoors Models;
 * The `ObjectBoundingboxHittester` is an R-Tree based data structure, making it possible to store arbitrary references (integers) with 2D rectangles.;
 */
@interface MIObjectBoundingboxHittester : NSObject

+ (nullable MIObjectBoundingboxHittester *)create;

- (void)addObjectWithBoundingBox:(double)north
                            east:(double)east
                           south:(double)south
                            west:(double)west
                       objectTag:(int32_t)objectTag;

- (nonnull NSArray<NSNumber *> *)objectsOverlappingPoint:(double)latitude
                                               longitude:(double)longitude;

- (nonnull NSArray<NSNumber *> *)objectsOverlappingRect:(double)north
                                                   east:(double)east
                                                  south:(double)south
                                                   west:(double)west;

- (void)updateObjectWithBoundingBox:(double)north
                               east:(double)east
                              south:(double)south
                               west:(double)west
                          objectTag:(int32_t)objectTag;

- (void)removeObjectsWithTags:(nonnull NSArray<NSNumber *> *)tags;

@end
