// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIOrdering.h"
#include "../cpp/Ordering.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIOrdering;

namespace djinni_generated {

struct Ordering
{
    using CppType = ::MICommon::Ordering;
    using ObjcType = MIOrdering*;

    using Boxed = Ordering;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
