// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MICoordinate.h"
#import <Foundation/Foundation.h>

@interface MIPath : NSObject
- (nonnull instancetype)initWithCoordinates:(nonnull NSArray<MICoordinate *> *)coordinates;
+ (nonnull instancetype)PathWithCoordinates:(nonnull NSArray<MICoordinate *> *)coordinates;

@property (nonatomic, readonly, nonnull) NSArray<MICoordinate *> * coordinates;

@end
