// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIPath.h"
#import <Foundation/Foundation.h>

@interface MIPolygon : NSObject
- (nonnull instancetype)initWithOuterRing:(nonnull MIPath *)outerRing
                               innerRings:(nonnull NSArray<MIPath *> *)innerRings;
+ (nonnull instancetype)PolygonWithOuterRing:(nonnull MIPath *)outerRing
                                  innerRings:(nonnull NSArray<MIPath *> *)innerRings;

@property (nonatomic, readonly, nonnull) MIPath * outerRing;

@property (nonatomic, readonly, nonnull) NSArray<MIPath *> * innerRings;

@end
