// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIQuery.h"
#include "../cpp/Query.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIQuery;

namespace djinni_generated {

struct Query
{
    using CppType = ::MICommon::Query;
    using ObjcType = MIQuery*;

    using Boxed = Query;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
