// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import <Foundation/Foundation.h>

/** A simple rectangle model.; */
@interface MIRect : NSObject
- (nonnull instancetype)initWithX:(double)x
                                y:(double)y
                            width:(double)width
                           height:(double)height;
+ (nonnull instancetype)RectWithX:(double)x
                                y:(double)y
                            width:(double)width
                           height:(double)height;

@property (nonatomic, readonly) double x;

@property (nonatomic, readonly) double y;

@property (nonatomic, readonly) double width;

@property (nonatomic, readonly) double height;

@end
