//
//  MapsIndoorSDK.h"
//  MapsIndoorSDK
//
//  Created by Daniel Nielsen on 26/02/14.
//  Copyright (c) 2014 MapsPeople A/S. All rights reserved.
//



#import "UIColor+HexString.h"
#import "MPAppData.h"
#import "MPAppDataProvider.h"
#import "MPAppMode.h"
#import "MPBuilding.h"
#import "MPBuildingDataset.h"
#import "MPCategoryUIBarButtonItem.h"
#import "MPCachedLocationsProvider.h"
#import "MPContactModule.h"
#import "MPFloor.h"
#import "MPFloorButton.h"
#import "MPFloorSelectorControl.h"
#import "MPFloorTileLayer.h"
#import "MPGeometry.h"
#import "MPInfoSnippetView.h"
#import "MPLatLng.h"
#import "MPLatLngBounds.h"
#import "MPLayerType.h"
#import "MPLineGeometry.h"
#import "MPLoadIndicator.h"
#import "MPLocation.h"
#import "MPLocationDataset.h"
#import "MPLocationDisplayRule.h"
#import "MPLocationDisplayRuleset.h"
#import "MPLocationProperty.h"
#import "MPLocationPropertyTableCell.h"
#import "MPLocationPropertyView.h"
#import "MPLocationsProvider.h"
#import "MPLocationTableViewController.h"
#import "MPLocationView.h"
#import "MPMapControl.h"
#import "MPMapStyle.h"
#import "MPOfflineTileLayer.h"
#import "MPOnlineTileLayer.h"
#import "MPOpeningHours.h"
#import "MPOpeningHoursModule.h"
#import "MPPoint.h"
#import "MPRouteStep.h"
#import "MPRoute.h"
#import "MPRouteInfo.h"
#import "MPRouteLeg.h"
#import "MPRoutingControl.h"
#import "MPRoutingProvider.h"
#import "MPSearchDisplayController.h"
#import "MPSite.h"
#import "MPTileDB.h"
#import "MPTokenSet.h"
#import "MPUIViewController.h"
#import "MPURITemplate.h"
#import "MPVector.h"
#import "MPVenue.h"
#import "MPVenueCollection.h"
#import "MPVenueProvider.h"
#import "NSString+FontAwesome.h"
#import "NSURL+QueryParser.h"
#import "UIFont+FontAwesome.h"
#import "UIFont+RegisterURL.h"
#import "MPLocationQuery.h"
#import "MPMapExtend.h"
#import "MPPositionProvider.h"
#import "MPBeaconPositionProvider.h"
#import "MPDistanceMatrixProvider.h"
#import "MPDirectionsService.h"
#import "MPImageRenderer.h"
#import "MPDirectionsRenderer.h"
#import "MPMapRouteLegButton.h"
#import "MPMyLocationButton.h"
#import "MPBeacon.h"
#import "MPDouble.h"
#import "PositionCalculator.h"
