#import "LocalizationSystem.h"

#define kLangLang MPLocalizedString(@"Lang", @"Sprogkode")
#define kLangAppName MPLocalizedString(@"SDU Map", @"SDU Kort")
#define kLangBuilding MPLocalizedString(@"Building", @"Bygning")
#define kLangFloor MPLocalizedString(@"Floor", @"Etage")
#define kLangLevel MPLocalizedString(@"Level", @"Etage")
#define kLangLevel_var MPLocalizedString(@"Level %@", @"Etage %@")
#define kLangPlease_enable_WIFI MPLocalizedString(@"Please enable WIFI", @"Slå WIFI til")
#define kLangEnableWIFIToGetPositioning MPLocalizedString(@"In order to determine your position WIFI must be enabled and the phone must be connected to the University network", @"For at finde din indendørs position skal wifi være tændt og forbundet til KUs netværk.")
#define kLangOK MPLocalizedString(@"OK", @"OK")
#define kLangGet_directions MPLocalizedString(@"Get directions", @"Find vej")
#define kLangOrigin MPLocalizedString(@"Starting point", @"Start lokation")
#define kLangDestination MPLocalizedString(@"Destination", @"Destination")
#define kLangChoose_destination MPLocalizedString(@"Choose destination", @"Vælg ønsket destination.")
#define kLangChoose_origin MPLocalizedString(@"Choose starting point", @"Vælg ønsket udgangspunkt for ruten.")
#define kLangPlease_review_your_selections_and_try_again MPLocalizedString(@"Please review your selections and try again", @"Tjek venligst din indtastning og prøv igen.")
#define kLangSelected_position MPLocalizedString(@"Chosen position", @"Valgt placering")
#define kLangRoom_ID MPLocalizedString(@"Room ID", @"Rum ID")
#define kLangMark_a_position MPLocalizedString(@"Mark a position", @"Vælg ønsket placering")
#define kLangUse_this_position MPLocalizedString(@"Use this position", @"Brug denne position?")
#define kLangMap MPLocalizedString(@"Map", @"Kort")
#define kLangLanguage MPLocalizedString(@"Language", @"Sprog")
#define kLangDanish MPLocalizedString(@"Danish", @"Dansk")
#define kLangEnglish MPLocalizedString(@"English", @"Engelsk")
#define kLangWhere_am_I MPLocalizedString(@"Where am I", @"Hvor er jeg?")
#define kLangWorkspaces MPLocalizedString(@"Workspaces", @"Studiearbejdspladser")
#define kLangSocial_rooms MPLocalizedString(@"Social rooms", @"Sociale opholdsrum")
#define kLangSocial_roomsKey MPLocalizedString(@"Social rooms key", @"Sociale opholdsrum id")
#define kLangClassrooms MPLocalizedString(@"Classrooms", @"Undervisning")
#define kLangMeeting_rooms MPLocalizedString(@"Meeting rooms", @"Mødelokale")
#define kLangOffices MPLocalizedString(@"Offices", @"Kontor")
#define kLangRestrooms MPLocalizedString(@"Restrooms", @"Toilet")
#define kLangServices MPLocalizedString(@"Services", @"Services")
#define kLangStaircase MPLocalizedString(@"Staircase", @"Trappe")
#define kLangElevator MPLocalizedString(@"Elevator", @"Elevator")
#define kLangCategories MPLocalizedString(@"Categories", @"Kategorier")
#define kLangSearch MPLocalizedString(@"Search", @"Søg")
#define kLangSearch_var MPLocalizedString(@"Search %@", @"Søg i %@")
#define kLangShow MPLocalizedString(@"Show", @"Vis")
#define kLangShow_on_map MPLocalizedString(@"Show on map", @"Vis på kort")
#define kLangShowing_route MPLocalizedString(@"Showing route...", @"Viser rute...")
#define kLangMinutes_walk MPLocalizedString(@"%d minutes walk", @"%d minutters gang")
#define kLangFrom MPLocalizedString(@"From", @"Fra")
#define kLangTo MPLocalizedString(@"To", @"Til")
#define kLangNext MPLocalizedString(@"Next", @"Næste")
#define kLangPrev MPLocalizedString(@"Previous", @"Forrige")
#define kLangReport_this_location MPLocalizedString(@"Report this location", @"Rapportér POI?")
#define kLangTap_to_compose_email MPLocalizedString(@"Tap to compose email", @"Tryk for at sende email")
#define kLangMy_position MPLocalizedString(@"My position", @"Min placering")
#define kLangGPS_Warning MPLocalizedString(@"GPS Warning", @"Du befinder dig i tæt bebygget område hvor GPS-signalet kan forringes. Bevæger du dig indendørs kan du ikke forvente god GPS-position.")
#define kLangNearby_search MPLocalizedString(@"Nearby search", @"Søg i nærheden")
#define kLangAdd MPLocalizedString(@"Add", @"Tilføj")
#define kLangType MPLocalizedString(@"Type", @"Indtast")
#define kLangNo_data_is_available MPLocalizedString(@"No data is available", @"Ingen data er tilgængelige")
#define kLangFind_nearest MPLocalizedString(@"Find nearest", @"Find nærmeste")
#define kLangDetails MPLocalizedString(@"Details", @"Detaljer")
#define kLangCompass MPLocalizedString(@"Compass", @"Kompas")
#define kLangSatellite MPLocalizedString(@"Satellite", @"Satellit")
#define kLangFavourites MPLocalizedString(@"Favourites", @"Favoritter")
#define kLangTrack_my_position MPLocalizedString(@"Track my position", @"Følg min position")
#define kLangUse_positioning MPLocalizedString(@"Use positioning", @"Brug positionering")
#define kLangArrival MPLocalizedString(@"Arrival", @"Ankomst")
#define kLangDeparture MPLocalizedString(@"Departure", @"Afgang")
#define kLangShow_all MPLocalizedString(@"Show all", @"Vis alle")
#define kLangOpen_menu MPLocalizedString(@"Open menu", @"Åben menu")
#define kLangClose_menu MPLocalizedString(@"Close menu", @"Luk menu")
#define kLangMenu MPLocalizedString(@"Menu", @"Menu")
#define kLangUse_elevators MPLocalizedString(@"Use elevators", @"Brug elevator")
#define kLangNearest MPLocalizedString(@"Nearest", @"Nærmeste")
#define kLangTap_on_the_map_to_mark_a_location MPLocalizedString(@"Tap on the map to mark a location", @"Tryk på kortet for at markere en lokation")
#define kLangDirection MPLocalizedString(@"Direction", @"Retning")
#define kLangUnfortuneately_no_locations_are_available MPLocalizedString(@"Unfortuneately no locations are available", @"Der er desværre ingen lokationer tilgængelig.")
#define kLangCould_not_find_any_route MPLocalizedString(@"Could not find any route", @"Kunne ikke finde en rute.")
#define kLangPlease_select_both_an_origin_and_a_destination MPLocalizedString(@"Please select both a starting point and a destination", @"Vælg venligst både en start lokation og en destination.")
#define kLangSearching_for MPLocalizedString(@"Searching for", @"Søger efter")
#define kLangSearching_for_var MPLocalizedString(@"Searching for '%@'", @"Søger efter '%@'")
#define kLangSwitch_direction MPLocalizedString(@"Switch direction", @"Skift retning")
#define kLangReportSuggest_location MPLocalizedString(@"Reportsuggest location", @"Rapportér/foreslå POI")
#define kLangTap_on_the_map_to_mark_a_suggestion_for_a_new_location MPLocalizedString(@"Tap on the map to mark a suggestion for a new location", @"Tryk på kortet for at markere et forslag til ny lokation/POI.")
#define kLangCancel MPLocalizedString(@"Cancel", @"Fortryd")
#define kLangSelect_venue MPLocalizedString(@"Select Venue", @"Vælg sted")
#define kLangStudy_spaces MPLocalizedString(@"Study spaces", @"Studiearbejdspladser")
#define kLangGroup_rooms MPLocalizedString(@"Group rooms", @"Grupperum")
#define kLangCanteen MPLocalizedString(@"Canteen", @"Kantine")
#define kLangDefibrillator MPLocalizedString(@"Defibrillator", @"Hjertestarter")
#define kLangThesis_study_spaces MPLocalizedString(@"Thesis study spaces", @"Specialelæseplads")
#define kLangPrint MPLocalizedString(@"Print", @"Print")
#define kLangCopy_machines MPLocalizedString(@"Copy machines", @"Kopi")
#define kLangComputer MPLocalizedString(@"Computer", @"EDB")
#define kLangCafe MPLocalizedString(@"Cafe", @"Cafe")
#define kLangKiosk MPLocalizedString(@"Kiosk", @"Kiosk")
#define kLangSearchResult MPLocalizedString(@"Search Result", @"Viser søgning")
#define kLangClear_map MPLocalizedString(@"Clear map", @"Ryd kort")
#define kLangMarkPosition MPLocalizedString(@"Mark a position", @"Markér en position")
#define kLangStart MPLocalizedString(@"Start", @"Start")
#define kLangStairs_and_elevators MPLocalizedString(@"Stairs and elevators", @"Trappe og elevator")
#define kLangLangHasChanged MPLocalizedString(@"Language has been changed", @"Sproget er skiftet")
#define kLangRestartAppAndSwitchLang MPLocalizedString(@"Restart app and switch language", @"Genstart app og skift sprog")
#define kLangLangSwitchRequiresAppRestart MPLocalizedString(@"Language switch requires app restart", @"Sprogskift kræver at appen genstarter")
#define kLangAvoidStairs MPLocalizedString(@"Avoid stairs", @"Undgå trapper")
#define kLangCouldNotFindLocations MPLocalizedString(@"Sorry, failed to get locations...", @"Sorry, failed to get locations...")
#define kLangCouldNotFindContent MPLocalizedString(@"Sorry, failed to get app content...", @"Sorry, failed to get app content...")
#define kLangCouldNotFindLocationDetails MPLocalizedString(@"Sorry, failed to get location details...", @"Sorry, failed to get location details...")
#define kLangCouldNotFindDirections MPLocalizedString(@"Sorry, failed to get directions...", @"Sorry, failed to get directions...")