#import "LocalizationSystem.h"

#define kLangLang                           MPLocalizedString(@"Language", @"")
#define kLangLevel                          MPLocalizedString(@"Level", @"")
#define kLangLevelVar                       MPLocalizedString(@"Level %@", @"")
#define kLangGetDirections                  MPLocalizedString(@"Get directions", @"")
#define kLangChooseDestination              MPLocalizedString(@"Choose destination", @"")
#define kLangChooseOrigin                   MPLocalizedString(@"Choose starting point", @"")
#define kLangCategories                     MPLocalizedString(@"Categories", @"")
#define kLangSearch                         MPLocalizedString(@"Search", @"")
#define kLangSearchVar                      MPLocalizedString(@"Search %@", @"")
#define kLangShowOnMap                      MPLocalizedString(@"Show on map", @"")

#define kLangMinutes                        MPLocalizedString(@"%d min", @"")
#define kLangHours                          MPLocalizedString(@"%d h", @"")
#define kLangHoursMinutes                   MPLocalizedString(@"%d h %d min walk", @"")
#define kLangDays                           MPLocalizedString(@"%d d", @"")
#define kLangDaysHours                      MPLocalizedString(@"%d d %d h",@"")
#define kLangDaysHoursMinutes               MPLocalizedString(@"%d d %d h %d min",@"")

#define kLangByWalk                         MPLocalizedString(@"walk", @"")
#define kLangByCar                          MPLocalizedString(@"by car", @"")
#define kLangByCycling                      MPLocalizedString(@"by bike", @"")
#define kLangByTransit                      MPLocalizedString(@"by transit", @"")
#define kLangExit                           MPLocalizedString(@"Enter", @"")
#define kLangEnter                          MPLocalizedString(@"Exit", @"")


#define kLangEstimatedPosNearVar            MPLocalizedString(@"Estimated: %@", @"")
#define kLangFromPosVar                     MPLocalizedString(@"From %@", @"")
#define kLangNext                           MPLocalizedString(@"Next", @"")
#define kLangPrev                           MPLocalizedString(@"Previous", @"")
#define kLangMyPosition                     MPLocalizedString(@"My position", @"")
#define kLangSearchingForVar                MPLocalizedString(@"Searching for '%@'", @"")
#define kLangSelectVenue                    MPLocalizedString(@"Select Venue", @"")
#define kLangSearchResult                   MPLocalizedString(@"Search Result", @"")
#define kLangAvoidStairs                    MPLocalizedString(@"Avoid stairs", @"")
#define kLangCouldNotFindLocations          MPLocalizedString(@"Sorry, failed to get locations...", @"")
#define kLangCouldNotFindContent            MPLocalizedString(@"Sorry, failed to get app content...", @"")
#define kLangCouldNotFindLocationDetails    MPLocalizedString(@"Sorry, failed to get location details...", @"")
#define kLangCouldNotFindDirections         MPLocalizedString(@"Sorry, failed to get directions...", @"")
#define kLangFeedback                       MPLocalizedString(@"Got feedback?", @"")
#define kLangFeedbackSendEmail              MPLocalizedString(@"Send us an email", @"")
#define kLangPleaseEnableWIFI               MPLocalizedString(@"Please enable WIFI", @"")
#define kLangEnableWIFIToGetPositioning     MPLocalizedString(@"In order to determine your position WIFI must be enabled and the phone must be connected to the Wifi network", @"")

#define kLangSplashWelcome                  MPLocalizedString(@"Welcome to the map service of MapsPeople", @"")
#define kLangSplashLoading                  MPLocalizedString(@"Buildings and rooms are being loaded", @"")

#define kLangSearchNoMatch                  MPLocalizedString(@"No matches for \"%@\"", @"" )
#define kLangSearchNoLocations              MPLocalizedString(@"No locations to show", @"" )
#define kLangUseSearchToSearchFormat        MPLocalizedString(@"Use the search to search across\n%@", @"" )
#define kLangUseSearchToSearchFormatAccess  MPLocalizedString(@"Use the searchfield at the top to search across\n%@", @"" )
#define kLangSearchLocationsIndoorsAndOutdoors  MPLocalizedString(@"Search for locations indoors and outdoors", @"" )

#define kLangNoRouteFound                   MPLocalizedString(@"No route found", @"" )

#define kLangCancel                         MPLocalizedString(@"Cancel",@"")

#define kLangReturnToVenue                  MPLocalizedString(@"RETURN TO VENUE",@"")
#define kLangZoomForMoreDetails             MPLocalizedString(@"Zoom for more details",@"")

// Location services alerts
#define kLangLocationServicesDisabled       MPLocalizedString(@"Location Services are disabled",@"")
#define kLangTurnOnLocationServices         MPLocalizedString(@"Please turn on your phone's location services from privacy settings for us to determine your location.",@"")
#define kLangTurnOnLocationServicesForApp   MPLocalizedString(@"Please turn on location services for %@ to determine your location.",@"")
#define kLangTurnOn                         MPLocalizedString(@"Turn On",@"")
#define kLangSettings                       MPLocalizedString(@"Settings",@"")
#define kLangTurOnLocationInDirections      MPLocalizedString( @"Turn on location services to get your estimated position", @"")
#define kLangTurOnLocationInDirectionsAbbr  MPLocalizedString( @"Turn on location services", @"")

#define kLangClearMap                       MPLocalizedString(@"  Clear Map  ", @"")

#define kLangFind                           MPLocalizedString(@"Find", @"")

// Offline UI
#define kLangNoInternetUnableToUpdateMap    MPLocalizedString(@"No Internet, unable to update map",@"")
#define kLangOfflineTryToReconnect          MPLocalizedString(@"NO INTERNET - TRY TO RECONNECT",@"")
#define kLangInitOfflineWithDataAvailable   MPLocalizedString( @"No Internet - Previously loaded content available", @"" )
#define kLangInitOfflineDataUnavailable     MPLocalizedString( @"No Internet - Failed to get app content", @"" )
#define kLangNoInternet                     MPLocalizedString( @"No Internet", @"" )
#define kLangNoInternetMessage              MPLocalizedString( @"kLangNoInternetMessage", @"" )
#define kLangNoInternetNoGoogleResults      MPLocalizedString( @"No Internet - No Google results", @"" )

// Transit sources
#define kLangWebsite                        MPLocalizedString( @"Website", @"" )
#define kLangPhone                          MPLocalizedString( @"Phone", @"" )
#define kLangOpenInSafariQ                  MPLocalizedString( @"Open in Safari ?", @"" )
#define kLangOpen                           MPLocalizedString( @"Open", @"" )
#define kLangPhoneNumberCopiedToClipboard   MPLocalizedString( @"Phone number copied to clipboard", @"" )

// Directions
#define kLangTransitStopsFmt                MPLocalizedString( @"%d stops (%@)", @"" )
#define kLangDurationEstimateNotAvailable   MPLocalizedString( @"Duration estimate not available", @"" )
#define kLangPleaseChooseStartingPoint      MPLocalizedString( @"Please choose starting point", @"" )
#define kLangPleaseChooseDestination        MPLocalizedString( @"Please choose destination", @"" )

#pragma mark - Accessibility string
#define kLangExitVenueSelectorAccHint       MPLocalizedString( @"Exit venue selector", @"" )
#define kLangSelectVenueAccHint             MPLocalizedString( @"Select Venue", @"" )
#define kLangCurrentVenueAccHint            MPLocalizedString( @"Current Venue", @"" )
#define kLangShowCategoryAccHint            MPLocalizedString( @"Show Category", @"" )
#define kLangNumResultsAvailableAccHint     MPLocalizedString( @"%@ Results available", @"" )
#define kLangBackAccHint                    MPLocalizedString( @"Back", @"" )
#define kLangSelectRouteOriginAccHint       MPLocalizedString( @"Select route origin", @"" )
#define kLangSelectRouteDestinationAccHint  MPLocalizedString( @"Select route destination", @"" )
#define kLangSwapRouteStartAndDestinationAccHint  MPLocalizedString( @"Swap route start and destination", @"" )
#define kLangAvoidStairsOnAccHint           MPLocalizedString( @"Avoid Stairs On, double tap to change.", @"" )
#define kLangAvoidStairsOffAccHint          MPLocalizedString( @"Avoid Stairs Off, double tap to change.", @"" )
#define kLangFindingRouteAccHint            MPLocalizedString( @"Finding Route", @"" )
#define kLangRouteAvailableAccHint          MPLocalizedString( @"Route available : %@", @"" )
#define kLangShowSidebarAccLabel            MPLocalizedString( @"Show Side Bar Menu", @"" )
#define kLangHideSidebarAccLabel            MPLocalizedString( @"Hide Side Bar Menu", @"" )
#define kLangSelectFloorNAccLabel           MPLocalizedString( @"Select Floor %@", @"" )
#define kLangFindNearestAccLabel            MPLocalizedString( @"Find nearest shortcut menu", @"" )
#define kLangShowCategoryButtonAccLabel     MPLocalizedString( @"Show Category: %@", @"" )
#define kLangTrackingDisabled               MPLocalizedString( @"Tracking disabled", @"" )
#define kLangTrackingOff                    MPLocalizedString( @"Tracking Off", @"" )
#define kLangTrackingOn                     MPLocalizedString( @"Tracking On", @"" )
#define kLangTrackingOnWithHeading          MPLocalizedString( @"Tracking On With Heading", @"" )
#define kLangChangeTrackingState            MPLocalizedString( @"Change tracking options", @"" )
#define kLangShowAppInfo                    MPLocalizedString( @"Show App Information", @"" )
#define kLangRouteSectionDescrPublicTransportAccLabel   MPLocalizedString( @"Drive %@ stops with public transport, %@ %@", @"" )
#define kLangRouteSectionDescrWalkAccLabel              MPLocalizedString( @"Walk", @"" )
#define kLangRouteSectionDescrCycleccLabel              MPLocalizedString( @"Bike", @"" )
#define kLangRouteSectionDescrDriveAccLabel             MPLocalizedString( @"Drive", @"" )
#define kLangStartRouteFromAccLabel                     MPLocalizedString( @"Start Route from %@, ", @"" )
#define kLangContinueRouteFromAccLabel                  MPLocalizedString( @"Continue Route from %@, ", @"" )
#define kLangContinueRouteAgainstAccLabel               MPLocalizedString( @"towards %@, ", @"" )
#define kLangContinueRouteAgainstDestAccLabel           MPLocalizedString( @"towards destination %@, ", @"" )
#define kLangRouteDirectionsPagingAccAnnouncement       MPLocalizedString( @"Route instructions %@ to %@ of %@", @"" )
#define kLangUserLocationMarkerAccLabel                 MPLocalizedString( @"My Location", @"" )
#define kLangUserLocationAccuracyAccLabel               MPLocalizedString( @"My location, accuracy %@m", @"" )

#define kLangLoginGo                                    MPLocalizedString( @"Go", @"" )
#define kLangLoginEnterSolutionId                       MPLocalizedString( @"Indtast solution-Id eller API-nøgle", @"" )
#define kLangLoginTryAGain                              MPLocalizedString( @"Ups. Prøv igen.", @"" )
#define kLangLogOut                                     MPLocalizedString( @"Log ud", @"" )
