// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SharedInterface.djinni

#import <Foundation/Foundation.h>

/** Geographic coordinate set, as latitude and longitude angles.; */
@interface MICoordinate : NSObject
- (nonnull instancetype)initWithLat:(double)lat
                                lng:(double)lng;
+ (nonnull instancetype)CoordinateWithLat:(double)lat
                                      lng:(double)lng;

/** Latitude angle; */
@property (nonatomic, readonly) double lat;

/** Longitude angle; */
@property (nonatomic, readonly) double lng;

@end
