// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SharedInterface.djinni

#import "MICoordinate.h"
#include "../cpp/Coordinate.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MICoordinate;

namespace djinni_generated {

struct Coordinate
{
    using CppType = ::MICommon::Coordinate;
    using ObjcType = MICoordinate*;

    using Boxed = Coordinate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
