// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MICoordinateBounds.h"
#include "../cpp/CoordinateBounds.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MICoordinateBounds;

namespace djinni_generated {

struct CoordinateBounds
{
    using CppType = ::MICommon::CoordinateBounds;
    using ObjcType = MICoordinateBounds*;

    using Boxed = CoordinateBounds;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
