// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MIHighwayType.h"
#import "MINode.h"
#import <Foundation/Foundation.h>

/**
 *################################################# DIRECTIONS, PATH OPTIMIZATIONS AND DEPENDENCIES  ########################################################
 * Route network edge model.;
 */
@interface MIEdge : NSObject
- (nonnull instancetype)initWithU:(nonnull MINode *)u
                                v:(nonnull MINode *)v
                      highwayType:(MIHighwayType)highwayType
                         distance:(int32_t)distance
                          context:(nonnull NSString *)context
                         waittime:(int32_t)waittime;
+ (nonnull instancetype)EdgeWithU:(nonnull MINode *)u
                                v:(nonnull MINode *)v
                      highwayType:(MIHighwayType)highwayType
                         distance:(int32_t)distance
                          context:(nonnull NSString *)context
                         waittime:(int32_t)waittime;

/** Node at the start of the edge; */
@property (nonatomic, readonly, nonnull) MINode * u;

/** Node at the end of the edge.; */
@property (nonatomic, readonly, nonnull) MINode * v;

/** Way type of = record the edge.; */
@property (nonatomic, readonly) MIHighwayType highwayType;

/** The distance of the edge in millimeters.; */
@property (nonatomic, readonly) int32_t distance;

/** The context of the edge. Can be anything, including "OutsideOnVenue", "InsideBuilding"; */
@property (nonatomic, readonly, nonnull) NSString * context;

@property (nonatomic, readonly) int32_t waittime;

@end
