// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

/** Float range containing a start and end float number.; */
@interface MIFloatRange : NSObject
- (nonnull instancetype)initWithStart:(float)start
                                  end:(float)end;
+ (nonnull instancetype)FloatRangeWithStart:(float)start
                                        end:(float)end;

/** Start of float range.; */
@property (nonatomic, readonly) float start;

/** End of float range.; */
@property (nonatomic, readonly) float end;

@end
