// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIGeometry.h"
#include "../cpp/Geometry.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIGeometry;

namespace djinni_generated {

struct Geometry
{
    using CppType = ::MICommon::Geometry;
    using ObjcType = MIGeometry*;

    using Boxed = Geometry;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
