// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIGroup.h"
#include "../cpp/Group.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIGroup;

namespace djinni_generated {

struct Group
{
    using CppType = ::MICommon::Group;
    using ObjcType = MIGroup*;

    using Boxed = Group;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
