// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MILocation.h"
#import "MILocationSourceStatus.h"
#import <Foundation/Foundation.h>
@protocol MILocationSource;


/** The `LocationObserver` interface is used for observing status changes and changes to the set of locations in a `LocationSource` or the `LocationService`.; */
@protocol MILocationsObserver

/** Notify the observer about updates to locations. Only the locations that were updated should be passed.; */
- (void)onLocationsUpdated:(nonnull NSArray<MILocation *> *)locations
                    source:(nullable id<MILocationSource>)source;

/** Notify the observer about location deletions. Pass a list of location ids referring to the locations that was recently deleted.; */
- (void)onLocationsDeleted:(nonnull NSArray<NSNumber *> *)locations
                    source:(nullable id<MILocationSource>)source;

/** Notify the observer about status changes.; */
- (void)onStatusChange:(MILocationSourceStatus)status
                source:(nullable id<MILocationSource>)source;

@end
