// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MILocation.h"
#include "../cpp/Location.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MILocation;

namespace djinni_generated {

struct Location
{
    using CppType = ::MICommon::Location;
    using ObjcType = MILocation*;

    using Boxed = Location;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
