// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#include "../cpp/LocationClusteringEngineDelegate.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MILocationClusteringEngineDelegate;

namespace djinni_generated {

class LocationClusteringEngineDelegate
{
public:
    using CppType = std::shared_ptr<::MICommon::LocationClusteringEngineDelegate>;
    using CppOptType = std::shared_ptr<::MICommon::LocationClusteringEngineDelegate>;
    using ObjcType = id<MILocationClusteringEngineDelegate>;

    using Boxed = LocationClusteringEngineDelegate;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

