// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#include "../cpp/LocationsObserver.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol MILocationsObserver;

namespace djinni_generated {

class LocationsObserver
{
public:
    using CppType = std::shared_ptr<::MICommon::LocationsObserver>;
    using CppOptType = std::shared_ptr<::MICommon::LocationsObserver>;
    using ObjcType = id<MILocationsObserver>;

    using Boxed = LocationsObserver;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

