// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#include "../cpp/LocationService.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MILocationService;

namespace djinni_generated {

class LocationService
{
public:
    using CppType = std::shared_ptr<::MICommon::LocationService>;
    using CppOptType = std::shared_ptr<::MICommon::LocationService>;
    using ObjcType = MILocationService*;

    using Boxed = LocationService;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

