// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MILocationDisplayMetadata.h"
#include "../cpp/LocationDisplayMetadata.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MILocationDisplayMetadata;

namespace djinni_generated {

struct LocationDisplayMetadata
{
    using CppType = ::MICommon::LocationDisplayMetadata;
    using ObjcType = MILocationDisplayMetadata*;

    using Boxed = LocationDisplayMetadata;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
