// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MICoordinate.h"
#import <Foundation/Foundation.h>

/** Route network node model.; */
@interface MINode : NSObject
- (nonnull instancetype)initWithPosition:(nonnull MICoordinate *)position
                                altitude:(float)altitude
                                  nodeId:(int32_t)nodeId
                   allowPathOptimization:(BOOL)allowPathOptimization;
+ (nonnull instancetype)NodeWithPosition:(nonnull MICoordinate *)position
                                altitude:(float)altitude
                                  nodeId:(int32_t)nodeId
                   allowPathOptimization:(BOOL)allowPathOptimization;

/** The node position in WGS84.; */
@property (nonatomic, readonly, nonnull) MICoordinate * position;

/** The altitude or floor index of the node.; */
@property (nonatomic, readonly) float altitude;

@property (nonatomic, readonly) int32_t nodeId;

/** indicates whether node.position may be modified by the path optimizer- */
@property (nonatomic, readonly) BOOL allowPathOptimization;

@end
