// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MINode.h"
#include "../cpp/Node.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MINode;

namespace djinni_generated {

struct Node
{
    using CppType = ::MICommon::Node;
    using ObjcType = MINode*;

    using Boxed = Node;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
