// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from HittesterInterface.djinni

#include "../cpp/ObjectBoundingboxHittester.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIObjectBoundingboxHittester;

namespace djinni_generated {

class ObjectBoundingboxHittester
{
public:
    using CppType = std::shared_ptr<::MICommon::ObjectBoundingboxHittester>;
    using CppOptType = std::shared_ptr<::MICommon::ObjectBoundingboxHittester>;
    using ObjcType = MIObjectBoundingboxHittester*;

    using Boxed = ObjectBoundingboxHittester;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

