// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

/** The `Ordering` object is used to setup ordering criteria for a search performed with `LocationService.getLocations()`. Ordering is set on a `Query` object.; */
@interface MIOrdering : NSObject
- (nonnull instancetype)initWithProperty:(nonnull NSString *)property
                               ascending:(BOOL)ascending;
+ (nonnull instancetype)OrderingWithProperty:(nonnull NSString *)property
                                   ascending:(BOOL)ascending;

/** Target property on `Location` that will determine the ordering; */
@property (nonatomic, readonly, nonnull) NSString * property;

/** Whether to sort ascending or descending. True (ascending) or false (descending); */
@property (nonatomic, readonly) BOOL ascending;

@end
