// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MIPath.h"
#include "../cpp/Path.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIPath;

namespace djinni_generated {

struct Path
{
    using CppType = ::MICommon::Path;
    using ObjcType = MIPath*;

    using Boxed = Path;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
