// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from SharedInterface.djinni

#import "MIPoint.h"
#include "../cpp/Point.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIPoint;

namespace djinni_generated {

struct Point
{
    using CppType = ::MICommon::Point;
    using ObjcType = MIPoint*;

    using Boxed = Point;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
