// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MIPolygon.h"
#include "../cpp/Polygon.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIPolygon;

namespace djinni_generated {

struct Polygon
{
    using CppType = ::MICommon::Polygon;
    using ObjcType = MIPolygon*;

    using Boxed = Polygon;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
