// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MIRect.h"
#include "../cpp/Rect.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIRect;

namespace djinni_generated {

struct Rect
{
    using CppType = ::MICommon::Rect;
    using ObjcType = MIRect*;

    using Boxed = Rect;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
