// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MIRoomPathSegment.h"
#include "../cpp/RoomPathSegment.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MIRoomPathSegment;

namespace djinni_generated {

struct RoomPathSegment
{
    using CppType = ::MICommon::RoomPathSegment;
    using ObjcType = MIRoomPathSegment*;

    using Boxed = RoomPathSegment;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
