// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DirectionsInterface.djinni

#import "MIEdge.h"
#import "MIPolygon.h"
#import <Foundation/Foundation.h>

@interface MIRoomPathSegment : NSObject
- (nonnull instancetype)initWithRoom:(nonnull MIPolygon *)room
                                path:(nonnull NSArray<MIEdge *> *)path;
+ (nonnull instancetype)RoomPathSegmentWithRoom:(nonnull MIPolygon *)room
                                           path:(nonnull NSArray<MIEdge *> *)path;

@property (nonatomic, readonly, nonnull) MIPolygon * room;

@property (nonatomic, readonly, nonnull) NSArray<MIEdge *> * path;

@end
