// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import <Foundation/Foundation.h>

/** A simple size model.; */
@interface MISize : NSObject
- (nonnull instancetype)initWithWidth:(double)width
                               height:(double)height;
+ (nonnull instancetype)SizeWithWidth:(double)width
                               height:(double)height;

@property (nonatomic, readonly) double width;

@property (nonatomic, readonly) double height;

@end
