// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClusteringInterface.djinni

#import "MISize.h"
#include "../cpp/Size.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MISize;

namespace djinni_generated {

struct Size
{
    using CppType = ::MICommon::Size;
    using ObjcType = MISize*;

    using Boxed = Size;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
