// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import "MITextProperty.h"
#include "../cpp/TextProperty.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MITextProperty;

namespace djinni_generated {

struct TextProperty
{
    using CppType = ::MICommon::TextProperty;
    using ObjcType = MITextProperty*;

    using Boxed = TextProperty;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
