// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from LocationInterface.djinni

#import <Foundation/Foundation.h>

/** Text property model. Contains a key, value and a language key.; */
@interface MITextProperty : NSObject
- (nonnull instancetype)initWithLanguage:(nonnull NSString *)language
                                     key:(nonnull NSString *)key
                                   value:(nonnull NSString *)value;
+ (nonnull instancetype)TextPropertyWithLanguage:(nonnull NSString *)language
                                             key:(nonnull NSString *)key
                                           value:(nonnull NSString *)value;

/** Text property language; */
@property (nonatomic, readonly, nonnull) NSString * language;

/** Text property key; */
@property (nonatomic, readonly, nonnull) NSString * key;

/** Text property value; */
@property (nonatomic, readonly, nonnull) NSString * value;

@end
