# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    xcode_select("/Applications/Xcode\ 13.4.1.app")
    cocoapods(podfile: "Example/Podfile")
  end

  desc "Test MapsIndoors app"
  lane :test_mapsindoors_app do
    run_tests(scheme: "MapsIndoors GitHub App")
  end

  desc "Test Demo app"
  lane :test_demo_app do
    run_tests(scheme: "Demos")
  end
end
